# Generated by Django 3.2.8 on 2021-10-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positionapp', '0001_initial'),
        ('listapp', '0002_alter_question_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='positionapp.position'),
        ),
    ]
